/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pck.eventplanner.jFrameUI.UserUI.innerMenues;

import com.pck.eventplanner.entity.Events;
import com.pck.eventplanner.entity.Users;
import com.pck.eventplanner.jdbe.EventDBMethods;
import com.pck.eventplanner.jdbe.UserDBMethods;
import com.pck.eventplanner.methods.TimeSlotProcessor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author G-Kesh
 */
public class EventAdder extends javax.swing.JFrame {
    static Users usr = new Users();
    ImageIcon img = new ImageIcon("E:\\Web projects\\Synergy\\$images$\\eventplanner.png");
    /**
     * Creates new form EventAdder
     */
    public EventAdder() {
        initComponents();
    }
     public EventAdder(Users usr) {
        initComponents();
        EventAdder.usr = usr;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescription = new javax.swing.JTextField();
        txtMinimumThreshold = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        BtnCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TxtEventName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInvitedAttendees = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtMinimumAttendees = new javax.swing.JTextField();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(img.getImage());

        txtDescription.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDescription.setText("Description");
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        txtMinimumThreshold.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMinimumThreshold.setText("Minimum Threshold");
        txtMinimumThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinimumThresholdActionPerformed(evt);
            }
        });

        BtnCreate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnCreate.setText("Create");
        BtnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCreateMouseClicked(evt);
            }
        });
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Caviar Dreams", 0, 36)); // NOI18N
        jLabel1.setText("Create Event");

        TxtEventName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtEventName.setText("Event Name");
        TxtEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEventNameActionPerformed(evt);
            }
        });

        txtLocation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLocation.setText("Location");

        txtInvitedAttendees.setColumns(20);
        txtInvitedAttendees.setRows(5);
        jScrollPane1.setViewportView(txtInvitedAttendees);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Invited attendees");

        txtMinimumAttendees.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMinimumAttendees.setText("Minimum Attendes");

        exit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(386, 386, 386)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(321, 321, 321)
                                    .addComponent(TxtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(321, 321, 321)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMinimumThreshold)
                                        .addComponent(jScrollPane1)
                                        .addComponent(txtMinimumAttendees)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(351, 351, 351))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMinimumThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtMinimumAttendees, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtMinimumThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinimumThresholdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinimumThresholdActionPerformed

    private void TxtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEventNameActionPerformed

    private void BtnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCreateMouseClicked
        EventDBMethods eVM = new EventDBMethods();
        UserDBMethods uD = new UserDBMethods();
        Events evta = new Events();
        evta.setName(TxtEventName.getText());
        evta.setLocation(txtLocation.getText());
        evta.setDescription(txtDescription.getText());
        evta.setMinAttendees(Integer.parseInt(txtMinimumAttendees.getText()));
        evta.setMinThres(Double.parseDouble(txtMinimumThreshold.getText()));
        evta.setAttendees(Arrays.asList(txtInvitedAttendees.getText().split(",")));
        for(String test : evta.getAttendees()){
            System.out.println(test);
        }
        boolean tru = eVM.addEvent(evta);

        if (tru) {
            JOptionPane.showMessageDialog(null, "Event Added!!");
        }
        List<Users> usrl, usr2 = new ArrayList<>();
        usrl = uD.showAll();
       usr.setEvent_planner(evta.getName());
       uD.editProfile(usr);
        for (Users usra : usrl) {
            for (String str : evta.getAttendees()) {
                if (usra.getFirst_name().equalsIgnoreCase(str)) {
                    usr2.add(usra);
                    StringBuilder sba = new StringBuilder();
                    sba.append(usra.getNotification()).append(",").append(evta.getName());
                    usra.setNotification(sba.toString());
                    uD.editProfile(usra);
                }
            }
        }
        TimeSlotProcessor tm = new TimeSlotProcessor();
        String[] ans = new String[6];
        ans = tm.timeSlotProcessor(usr2);
        evta.setSelDate(ans);
        boolean trth = eVM.selTimeSlot(ans, evta.getName());
        if (trth) {
            JOptionPane.showMessageDialog(null, "Date Selected!!");
        }
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_BtnCreateMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_exitMouseClicked

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        
    }//GEN-LAST:event_BtnCreateActionPerformed

    /**
     */
    public void eventAdder() {
        if(usr.getEvent_planner()!=null){
            JOptionPane.showMessageDialog(null, "You already have created an event."+usr.getEvent_planner()+"\n"+"Creating this event will overwrite the old event");
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventAdder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventAdder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventAdder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventAdder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EventAdder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreate;
    private javax.swing.JTextField TxtEventName;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextArea txtInvitedAttendees;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMinimumAttendees;
    private javax.swing.JTextField txtMinimumThreshold;
    // End of variables declaration//GEN-END:variables
}
