/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pck.eventplanner.jFrameUI.UserUI.innerMenues;

import com.pck.eventplanner.entity.Events;
import com.pck.eventplanner.entity.Users;
import com.pck.eventplanner.jdbe.EventDBMethods;
import com.pck.eventplanner.jdbe.UserDBMethods;
import com.pck.eventplanner.methods.TimeSlotProcessor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author G-Kesh
 */
public class UpdateEvent extends javax.swing.JFrame {
    ImageIcon img = new ImageIcon("E:\\Web projects\\Synergy\\$images$\\eventplanner.png");
    static Events evts = new Events();

    /**
     * Creates new form UpdateEvent
     */
    public UpdateEvent() {
        initComponents();
    }

    public UpdateEvent(Events evts) {
        initComponents();
        UpdateEvent.evts = evts;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtEventName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtMinimumThreshold = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtMinimumAttendes = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInvitedAttendees = new javax.swing.JTextArea();
        btnUpdate1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(img.getImage()
        );
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Caviar Dreams", 0, 24)); // NOI18N
        jLabel1.setText("Update Event");

        txtEventName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEventName.setText("Event Name");
        txtEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEventNameActionPerformed(evt);
            }
        });

        txtLocation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLocation.setText("Location");

        txtDescription.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDescription.setText("Description");
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        txtMinimumThreshold.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMinimumThreshold.setText("Minimum Threshold");
        txtMinimumThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinimumThresholdActionPerformed(evt);
            }
        });

        jLabel2.setText("Invited attendees");

        txtMinimumAttendes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMinimumAttendes.setText("Minimum Attendes");

        btnUpdate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        txtInvitedAttendees.setColumns(20);
        txtInvitedAttendees.setRows(5);
        jScrollPane2.setViewportView(txtInvitedAttendees);

        btnUpdate1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnUpdate1.setText("Cancel");
        btnUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEventName)
                                    .addComponent(txtLocation)
                                    .addComponent(txtDescription)
                                    .addComponent(txtMinimumThreshold, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtMinimumAttendes)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMinimumThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMinimumAttendes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtMinimumThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinimumThresholdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinimumThresholdActionPerformed

    private void btnUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnUpdate1MouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained


    }//GEN-LAST:event_formFocusGained

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        UserDBMethods uD = new UserDBMethods(); 
        List<Users> usrl, usr2 = new ArrayList<>();
        usrl = uD.showAll();
        for(Users tmpUsr: usrl){
            for(String usrn : evts.getAttendees()){
                if(usrn.equalsIgnoreCase(tmpUsr.getFirst_name())){
                    List<String> tmp,tmp2 = new ArrayList<>();
                    tmp = Arrays.asList(tmpUsr.getNotification().split(","));
                    for(String s : tmp){
                        if(!evts.getName().equalsIgnoreCase(s)){
                            tmp2.add(s);
                        }
                    }
                    tmpUsr.setNotification(tmpUsr.retString(tmp2));
                    uD.editProfile(tmpUsr);
                }
            }
        }
        evts.setName(txtEventName.getText());
        evts.setDescription(txtDescription.getText());
        evts.setAttendees(Arrays.asList(txtInvitedAttendees.getText().split(",")));
        evts.setLocation(txtLocation.getText());
        evts.setMinAttendees(Integer.parseInt(txtMinimumAttendes.getText()));
        evts.setMinThres(Double.parseDouble(txtMinimumThreshold.getText()));
        EventDBMethods eD = new EventDBMethods();
        boolean tr = eD.editEvent(evts);
       if(tr){
           JOptionPane.showMessageDialog(null, "Event Updated!!");
       }
        
        for (Users usra : usrl) {
            for (String str : evts.getAttendees()) {
                if (usra.getFirst_name().equalsIgnoreCase(str)) {
                    usr2.add(usra);
                    StringBuilder sba = new StringBuilder();
                    sba.append(usra.getNotification()).append(",").append(evts.getName());
                    usra.setNotification(sba.toString());
                    uD.editProfile(usra);
                }
            }
        }
        TimeSlotProcessor tm = new TimeSlotProcessor();
        String[] ans = new String[6];
        ans = tm.timeSlotProcessor(usr2);
        evts.setSelDate(ans);
        boolean trth = eD.selTimeSlot(ans, evts.getName());
        if (trth) {
            JOptionPane.showMessageDialog(null, "Date Selected!!");
        }
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtEventName.setText(evts.getName());
        txtDescription.setText(evts.getDescription());
        txtInvitedAttendees.setText(evts.getAttendeeString());
        txtLocation.setText(evts.getLocation());
        txtMinimumAttendes.setText(Integer.toString(evts.getMinAttendees()));
        txtMinimumThreshold.setText(Double.toString(evts.getMinThres()));
    }//GEN-LAST:event_formWindowActivated

    /**
     * @return
     */
    public Events updateEvt() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UpdateEvent().setVisible(true);
            }
        });
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextArea txtInvitedAttendees;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMinimumAttendes;
    private javax.swing.JTextField txtMinimumThreshold;
    // End of variables declaration//GEN-END:variables
}
