/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pck.eventplanner.jFrameUI.UserUI;

import com.pck.eventplanner.entity.Events;
import com.pck.eventplanner.entity.Users;
import com.pck.eventplanner.jFrameUI.UserUI.innerMenues.EventAdder;
import com.pck.eventplanner.jFrameUI.UserUI.innerMenues.UpdateEvent;
import com.pck.eventplanner.jFrameUI.UserUI.innerMenues.UpdateProfile;
import com.pck.eventplanner.jFrameUI.UserUI.innerMenues.ViewProfile;
import com.pck.eventplanner.jdbe.EventDBMethods;
import com.pck.eventplanner.jdbe.UserDBMethods;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author G-Kesh
 */
public class UserProfile extends javax.swing.JFrame {
    ImageIcon img = new ImageIcon("E:\\Web projects\\Synergy\\$images$\\eventplanner.png");
    static Users usr = new Users();

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
        extracomp();
    }

    public UserProfile(Users usr) {

        UserProfile.usr = usr;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usrnm = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        evnttbl = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menueventcreate = new javax.swing.JMenuItem();
        menuviewprofile = new javax.swing.JMenuItem();
        menuext = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        eventUpdate = new javax.swing.JMenuItem();
        profileEdit = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setIconImage(img.getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(167, 197, 216));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(186, 227, 237));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel1.setText("Hi,");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel2.setText(". Thank You For Logging In.");

        usrnm.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        usrnm.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usrnm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usrnm, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Getting Started", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        evnttbl.setBackground(new java.awt.Color(204, 255, 255));
        evnttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Events", "Descrption", "Day", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(evnttbl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Events", jPanel2);

        jMenu1.setText("Menu");

        menueventcreate.setText("Create Event");
        menueventcreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menueventcreateMouseClicked(evt);
            }
        });
        menueventcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueventcreateActionPerformed(evt);
            }
        });
        jMenu1.add(menueventcreate);

        menuviewprofile.setText("View Profile");
        menuviewprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewprofileActionPerformed(evt);
            }
        });
        jMenu1.add(menuviewprofile);

        menuext.setText("Log Out");
        menuext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuextMouseClicked(evt);
            }
        });
        menuext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuextActionPerformed(evt);
            }
        });
        jMenu1.add(menuext);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu2MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        eventUpdate.setText("Event");
        eventUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventUpdateMouseClicked(evt);
            }
        });
        eventUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventUpdateActionPerformed(evt);
            }
        });
        jMenu2.add(eventUpdate);

        profileEdit.setText("Profile");
        profileEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileEditMouseClicked(evt);
            }
        });
        profileEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileEditActionPerformed(evt);
            }
        });
        jMenu2.add(profileEdit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void extracomp() {
        evnttbl.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (evnttbl.getSelectedRow() > -1) {
                    int evntAccept = JOptionPane.YES_NO_OPTION;
                    int evntWin = JOptionPane.showConfirmDialog(null, "Do you want to attend this event?", "Attend Event", evntAccept);
                    if (evntWin == 0) {
                        //yes option 
                        JOptionPane.showMessageDialog(null, "Confirmation made!!");

                    } else {
                        //No option 
                        int reqRowIndex = evnttbl.getSelectedRow();
                        String selEvnt = (String) evnttbl.getModel().getValueAt(reqRowIndex, 1);
                        //Searching for selected event to clear the name
                        EventDBMethods eD = new EventDBMethods();
                        UserDBMethods uD = new UserDBMethods();
                        List<Events> evtLst = eD.showAll();
                        List<String> attendees = new ArrayList<>();
                        for (Events ev : evtLst) {
                            if (selEvnt.equalsIgnoreCase(ev.getName())) {
                                for (String str : ev.getAttendees()) {
                                    if (!str.equalsIgnoreCase(usr.getFirst_name())) {
                                        attendees.add(str);
                                    }
                                }
                                ev.setAttendees(attendees);
                                eD.editEvent(ev);
                            }
                        }
                        //Removing from notification
                        List<String> tmp = Arrays.asList(usr.getNotification().split(","));
                        List<String> newNot = new ArrayList<>();
                        for (String s : tmp) {
                            if (!s.equalsIgnoreCase(selEvnt)) {
                                newNot.add(s);
                            }
                        }
                        usr.setNotification(usr.retString(newNot));
                        uD.editProfile(usr);
                    }

                }
            }
        });
    }
    private void menuviewprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewprofileActionPerformed

        ViewProfile vW = new ViewProfile();
        vW.showProfile();

    }//GEN-LAST:event_menuviewprofileActionPerformed

    private void menueventcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueventcreateActionPerformed
        EventAdder eaD = new EventAdder(usr);
        eaD.eventAdder();
    }//GEN-LAST:event_menueventcreateActionPerformed

    private void menuextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuextMouseClicked

    }//GEN-LAST:event_menuextMouseClicked

    private void menuextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuextActionPerformed
        int lgoutAns = JOptionPane.YES_NO_OPTION;
        int ans = JOptionPane.showConfirmDialog(null, "Do you really wish to quit?", "Log Out", lgoutAns);
        if(ans == 0){
        setVisible(false);
        dispose(); //Destroy the JFrame object
        System.exit(0);
        }
    }//GEN-LAST:event_menuextActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered

    }//GEN-LAST:event_jPanel1MouseEntered

    private void menueventcreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueventcreateMouseClicked
        EventAdder eA = new EventAdder();
        eA.eventAdder();
    }//GEN-LAST:event_menueventcreateMouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered

    }//GEN-LAST:event_jTabbedPane1MouseEntered

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained

    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu2MenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MenuKeyPressed

    private void profileEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileEditMouseClicked

    }//GEN-LAST:event_profileEditMouseClicked

    private void eventUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventUpdateMouseClicked

    }//GEN-LAST:event_eventUpdateMouseClicked

    private void eventUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventUpdateActionPerformed
        if (!usr.getEvent_planner().equalsIgnoreCase("")) {
            EventDBMethods eD = new EventDBMethods();
            List<Events> evts = eD.showAll();
            Events usrEvt = new Events();
            for (Events temp : evts) {
                if (usr.getEvent_planner().equalsIgnoreCase(temp.getName())) {
                    usrEvt = temp;
                }
            }
            UpdateEvent uE = new UpdateEvent(usrEvt);
            uE.updateEvt();
        } else {
            JOptionPane.showMessageDialog(null, "You haven't created any events!!");
        }
    }//GEN-LAST:event_eventUpdateActionPerformed

    private void profileEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileEditActionPerformed
        UpdateProfile up = new UpdateProfile(usr);
        up.updateProfile();
    }//GEN-LAST:event_profileEditActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        usrnm.setText(usr.getFirst_name());
        EventDBMethods eD = new EventDBMethods();
        UserDBMethods uD = new UserDBMethods();
        List<Events> evtl = eD.showAll();
        DefaultTableModel dm = (DefaultTableModel) evnttbl.getModel();
        int rowCount =  dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        if (usr.getNotification() != null) {
            String[] events = usr.getNotification().split(",");
            for (Events evts : evtl) {
                for (String str : events) {
                    if (str.equalsIgnoreCase(evts.getName())) {
                        String[] temp = evts.getSelDate();
                        dm.addRow(new Object[]{evts.getId(), evts.getName(), evts.getDescription(), temp[0], evts.getLocation()});
                    }
                }
            }
            uD.editProfile(usr);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     */
    public void homeUI() {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem eventUpdate;
    private javax.swing.JTable evnttbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menueventcreate;
    private javax.swing.JMenuItem menuext;
    private javax.swing.JMenuItem menuviewprofile;
    private javax.swing.JMenuItem profileEdit;
    private javax.swing.JLabel usrnm;
    // End of variables declaration//GEN-END:variables
}
